import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { updateObjectField } from '../../util/object-utils';
import { mapWithDefault, Some } from '../../util/ts-belt/Option';
import { INITIAL_SINGLE_TOKEN_STATE } from '../constants';
import {
  Dialog,
  DialogBlock,
  DialogBody,
  DialogHeader,
  DialogSubmitButton,
} from '../styles';
import { MaybeTokenPair, Token } from '../types';
import {
  DialogFooter,
  RotateButton,
  RotateWrapper,
  SwapBlockHeader,
} from './styled';
import SwapInput from './SwapInput/SwapInput';

const SwapPage: NextPage = () => {
  const [tokens, setTokens] = useState<MaybeTokenPair>({
    firstToken: INITIAL_SINGLE_TOKEN_STATE,
    secondToken: INITIAL_SINGLE_TOKEN_STATE,
  });

  const handleTokenClick = (key: keyof MaybeTokenPair) => (token: Token) => {
    setTokens(
      updateObjectField(key, (value) => {
        return { ...value, tokenOption: Some(token) };
      }),
    );
  };

  const { firstToken, secondToken } = tokens;
  return (
    <>
      <Head>
        <title>Swap tokens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dialog>
        <DialogHeader>Swap tokens</DialogHeader>
        <DialogBody>
          <DialogBlock>
            <SwapBlockHeader>
              <span>From</span>
            </SwapBlockHeader>
            <SwapInput
              tokenWithAmount={firstToken}
              onTokenSelect={handleTokenClick('firstToken')}
              disabledTokens={mapWithDefault(
                secondToken.tokenOption,
                [],
                (token) => [token],
              )}
            />
          </DialogBlock>
          <RotateWrapper>
            <RotateButton>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#D9DBE9"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <line x1="12" y1="5" x2="12" y2="19" />
                <polyline points="19 12 12 19 5 12" />
              </svg>
            </RotateButton>
          </RotateWrapper>
          <DialogBlock>
            <SwapBlockHeader>
              <span>To</span>
            </SwapBlockHeader>
            <SwapInput
              tokenWithAmount={secondToken}
              onTokenSelect={handleTokenClick('secondToken')}
              disabledTokens={mapWithDefault(
                firstToken.tokenOption,
                [],
                (token) => [token],
              )}
            />
          </DialogBlock>
        </DialogBody>
        <DialogFooter>
          <DialogSubmitButton
            disabled={!(firstToken.tokenOption && secondToken.tokenOption)}
          >
            SWAP
          </DialogSubmitButton>
        </DialogFooter>
      </Dialog>
    </>
  );
};

export default SwapPage;
