import type { NextPage } from 'next';
import Head from 'next/head';
import { ChangeEventHandler, useEffect, useState } from 'react';
import { AVAILABLE_TOKENS } from '../constants';
import { DialogBody, DialogHeader, DialogSubmitButton } from '../styles';
import { Token, TokenPair } from '../types';
import {
  AnotherInputWrapper,
  CloseModalButton,
  Dialog,
  DialogBlock,
  DialogFooter,
  HourglassLoader,
  InputWrapper,
  MaxButton,
  Modal,
  ModalAmount,
  ModalContent,
  ModalSubmitButton,
  SuccessSign,
  SwapArrowBlock,
  SwapArrowWrapper,
  TildaWrapper,
  TokenAmountInput,
} from './styled';
import TokenSelector from './TokenSelector/TokenSelector';
import {
  MAX_INPUT,
  updateTokenState,
  useUpdateSecondTokenAmount,
} from './util';
import { SwapAsset } from '../../lib/tx-builder/types';
import { useCardanoWasmContext } from '../../context/cardano-wasm';
import { useNamiWalletContext } from '../../context/nami-wallet';
import { valueToAssets } from '../../lib/utils';

enum ModalState {
  HIDDEN,
  VISIBLE,
  LOADING,
  SUCCESS,
}

const AddLiquidityPage: NextPage = () => {
  const { wallet } = useNamiWalletContext();
  const { wasm } = useCardanoWasmContext();
  const [availableTokens, setAvailableTokens] = useState<SwapAsset[]>([]);
  const [tokens, setTokens] = useState<TokenPair>({
    firstToken: { token: availableTokens[0], amount: 0 },
    secondToken: { token: availableTokens[1], amount: 0 },
  });
  const [modalState, setModalState] = useState<ModalState>(ModalState.HIDDEN);

  const { firstToken, secondToken } = tokens;

  const getWalletAssets = async () => {
    if (!wallet || !wasm) {
      return [];
    }

    const utxoCbors = await wallet.getUtxos();
    const utxos = utxoCbors.map((utxoCbor) =>
      wasm.TransactionUnspentOutput.from_bytes(Buffer.from(utxoCbor, "hex"))
    );
    const assetsPerUtxo = await Promise.all(
      utxos.map((utxo) => valueToAssets(utxo.output().amount()))
    );

    return assetsPerUtxo.flat();
  };

  useUpdateSecondTokenAmount(firstToken, secondToken, setTokens);

  useEffect(() => {
    getWalletAssets().then((tokens) => {
      setAvailableTokens(tokens);
      handleTokenSelected("firstToken")(tokens[0]);
      handleTokenSelected("secondToken")(tokens[1]);
    });
  }, [wallet, wasm]);

  const handleTokenSelected = (key: keyof TokenPair) => (token: SwapAsset) => {
    setTokens(updateTokenState(key, 'token', token));
  };

  const handleMaxButtonClick = () => {
    setTokens(updateTokenState('firstToken', 'amount', MAX_INPUT));
  };

  const handleAmountChange: (
    key: keyof TokenPair,
  ) => ChangeEventHandler<HTMLInputElement> = (key) => (event) => {
    const int = parseInt(event.target.value);
    const amount = isNaN(int) ? 0 : int;

    setTokens(updateTokenState(key, 'amount', amount));
  };

  const showConfirmationModal = () => {
    setModalState(ModalState.VISIBLE);
  };

  const submitTransaction = () => {
    setModalState(ModalState.LOADING);
    setTimeout(() => {
      setModalState(ModalState.SUCCESS);
    }, 3000);
  };

  const closeModal = () => {
    setModalState(ModalState.HIDDEN);
  };

  return (
    <>
      <Head>
        <title>Add liquidity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dialog>
        <DialogHeader>Add liquidity</DialogHeader>
        <DialogBody>
          <DialogBlock>
            <TokenSelector
              availableTokens={availableTokens}
              selectedToken={firstToken.token}
              onTokenSelect={handleTokenSelected('firstToken')}
              disabledTokens={secondToken.token ? [secondToken.token] : []}
            />
            <InputWrapper>
              <AnotherInputWrapper>
                <MaxButton onClick={handleMaxButtonClick}>MAX</MaxButton>
                <TokenAmountInput
                  value={firstToken.amount}
                  placeholder="0.0"
                  onChange={handleAmountChange('firstToken')}
                />
              </AnotherInputWrapper>
            </InputWrapper>
          </DialogBlock>
          <SwapArrowBlock>
            <SwapArrowWrapper>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#D9DBE9"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <polyline points="19 12 12 19 5 12"></polyline>
              </svg>
            </SwapArrowWrapper>
          </SwapArrowBlock>
          <DialogBlock>
            <TokenSelector
              availableTokens={availableTokens}
              selectedToken={secondToken.token}
              onTokenSelect={handleTokenSelected('secondToken')}
              disabledTokens={firstToken.token ? [firstToken.token] : []}
            />
            <InputWrapper>
              <AnotherInputWrapper>
                <TildaWrapper>~</TildaWrapper>
                <TokenAmountInput
                  value={secondToken.amount}
                  placeholder="0.0"
                  disabled={true}
                />
              </AnotherInputWrapper>
            </InputWrapper>
          </DialogBlock>
        </DialogBody>
        <DialogFooter>
          <DialogSubmitButton
            disabled={!(firstToken.amount > 0)}
            onClick={showConfirmationModal}
          >
            Confirm adding liquidity
          </DialogSubmitButton>
        </DialogFooter>
        <Modal isActive={modalState !== ModalState.HIDDEN}>
          <ModalContent shouldCenterText={modalState !== ModalState.HIDDEN}>
            <CloseModalButton onClick={closeModal}>&#10006;</CloseModalButton>
            {modalState === ModalState.VISIBLE && (
              <>
                <p>You will receive</p>
                <ModalAmount>
                  {Math.round((secondToken.amount + Number.EPSILON) * 100) /
                    100}{' '}
                  {secondToken.token.name}
                </ModalAmount>
                <ModalSubmitButton onClick={submitTransaction}>
                  Confirm adding liquidity
                </ModalSubmitButton>
              </>
            )}
            {modalState === ModalState.LOADING && (
              <>
                <HourglassLoader />
                <h2>Waiting for confirmation</h2>
              </>
            )}
            {modalState === ModalState.SUCCESS && (
              <>
                <SuccessSign>&#10003;</SuccessSign>
                <h2>Transaction submitted</h2>
                <ModalSubmitButton onClick={closeModal}>
                  Close
                </ModalSubmitButton>
              </>
            )}
          </ModalContent>
        </Modal>
      </Dialog>
    </>
  );
};

export default AddLiquidityPage;
